[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3



# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/sokolsaiti"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Mastodon"
    url = "https://mastodon.social/@sokol"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/sokolsaiti"
    weight = 3